apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

bases:
  - ../../base

configMapGenerator:
  - name: velora-env-config
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=trace
      - TRACE_SAMPLING_RATIO=1.0
