apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

bases:
  - ../../base

patchesStrategicMerge: []

configMapGenerator:
  - name: velora-env-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - TRACE_SAMPLING_RATIO=1.0
