apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

bases:
  - ../../base

configMapGenerator:
  - name: velora-env-config
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=debug
      - TRACE_SAMPLING_RATIO=1.0
